Connected to snode (Python 3.10.14)

In [ ]:
import torch as t

weights = t.ones(4, requires_grad=True)

for epoch in range(1):
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    print(weights.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [ ]:
for epoch in range(2):
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    print(weights.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([6., 6., 6., 6.])
tensor(12., grad_fn=<SumBackward0>)
tensor([9., 9., 9., 9.])


In [ ]:
for epoch in range(3):
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    print(weights.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([12., 12., 12., 12.])
tensor(12., grad_fn=<SumBackward0>)
tensor([15., 15., 15., 15.])
tensor(12., grad_fn=<SumBackward0>)
tensor([18., 18., 18., 18.])


In [ ]:
for epoch in range(3):
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    weights.grad.zero_()
    print(weights.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([0., 0., 0., 0.])
tensor(12., grad_fn=<SumBackward0>)
tensor([0., 0., 0., 0.])
tensor(12., grad_fn=<SumBackward0>)
tensor([0., 0., 0., 0.])


In [ ]:
for epoch in range(3):
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [ ]:
weights = t.ones(2,3, requires_grad=True)

In [ ]:
weights = t.ones(2,3, requires_grad=True)

for epoch in range(3):
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor(18., grad_fn=<SumBackward0>)
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor(18., grad_fn=<SumBackward0>)
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor(18., grad_fn=<SumBackward0>)
tensor([[3., 3., 3.],
        [3., 3., 3.]])


In [ ]:
for epoch in range(3):

    print(weights.grad)
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    weights.grad.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(18., grad_fn=<SumBackward0>)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(18., grad_fn=<SumBackward0>)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(18., grad_fn=<SumBackward0>)


In [ ]:
weights = t.ones(2,3, requires_grad=True)

for epoch in range(3):

    print(weights.grad)
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    weights.grad.zero_()

None
tensor(18., grad_fn=<SumBackward0>)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(18., grad_fn=<SumBackward0>)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(18., grad_fn=<SumBackward0>)


In [ ]:
weights = t.ones(2,3, requires_grad=True)

for epoch in range(3):

    print(weights.grad)
    weights.grad.zero_()
    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()

None


AttributeError: 'NoneType' object has no attribute 'zero_'

In [ ]:
weights = t.ones(2,3, requires_grad=True)

for epoch in range(3):

    model_op = (weights*3).sum()
    print(model_op)
    print(weights.grad)
    weights.grad.zero_()
    model_op.backward()

tensor(18., grad_fn=<SumBackward0>)
None


AttributeError: 'NoneType' object has no attribute 'zero_'

In [ ]:
weights = t.ones(2,3, requires_grad=True)

for epoch in range(3):

    model_op = (weights*3).sum()
    print(model_op)
    model_op.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor(18., grad_fn=<SumBackward0>)
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor(18., grad_fn=<SumBackward0>)
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor(18., grad_fn=<SumBackward0>)
tensor([[3., 3., 3.],
        [3., 3., 3.]])


In [ ]:
import torch as t

weights = t.ones(2,3, requires_grad=True)

for epoch in range(3):

    model_op = weights*3
    print(model_op)
    op_mean = model_op.mean()
    op_add= op_mean.add(4)
    # weights.grad.zero_()
    op_add.backward()
    print(op_add.grad)
    print(op_mean.grad)
    print(model_op.grad)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<MulBackward0>)
None
None
None
tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<MulBackward0>)
None
None
None
tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<MulBackward0>)
None
None
None


<ipython-input-2-f058f24543da>:13: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(op_add.grad)
<ipython-input-2-f058f24543da>:14: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for mor

In [ ]:
for epoch in range(3):

    model_op = weights*3
    # print(model_op)
    op_mean = model_op.mean()
    op_add= op_mean.add(4)
    # weights.grad.zero_()
    op_add.backward()
    # print(op_add.grad)
    # print(op_mean.grad)
    # print(model_op.grad)
    print(weights.grad)

tensor([[3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])
tensor([[4.5000, 4.5000, 4.5000],
        [4.5000, 4.5000, 4.5000]])


In [ ]:
import torch as t

weights = t.ones(2, 3, requires_grad=True)

for epoch in range(3):
    model_op = (weights * 3)
    model_op.retain_grad()  # Retain gradient for non-leaf node
    op_mean = model_op.mean()
    op_mean.retain_grad()  # Retain gradient for non-leaf node
    op_add = op_mean.add(4)
    op_add.retain_grad()  # Retain gradient for non-leaf node
    
    op_add.backward()
    
    print("op_add.grad:", op_add.grad)
    print("op_mean.grad:", op_mean.grad)
    print("model_op.grad:", model_op.grad)
    print("weights.grad:", weights.grad)
    
    weights.grad.zero_()  # Reset gradients for next epoch

op_add.grad: tensor(1.)
op_mean.grad: tensor(1.)
model_op.grad: tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])
weights.grad: tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
op_add.grad: tensor(1.)
op_mean.grad: tensor(1.)
model_op.grad: tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])
weights.grad: tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
op_add.grad: tensor(1.)
op_mean.grad: tensor(1.)
model_op.grad: tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])
weights.grad: tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
