In [ ]:
import torch

x = torch.rand(3) 
print(x)

tensor([0.4810, 0.5623, 0.9896])


In [ ]:
x = torch.rand(1) 
print(x)

tensor([0.8227])


In [ ]:
x = torch.rand(2,1) 
print(x)

tensor([[0.1672],
        [0.1277]])


In [ ]:
x = torch.rand(2,1,2) 
print(x)

tensor([[[0.5094, 0.7397]],

        [[0.4219, 0.5556]]])


In [ ]:
x = torch.rand((2,1,2)) 
print(x)

tensor([[[0.7601, 0.8453]],

        [[0.4190, 0.6025]]])


In [ ]:
x = torch.rand((2,2,1)) 
print(x)

tensor([[[0.4488],
         [0.8911]],

        [[0.4460],
         [0.2721]]])


In [ ]:
x = torch.rand((1,2,1)) 
print(x)

tensor([[[0.4739],
         [0.3564]]])


In [ ]:
x = torch.rand((1,1,1,1)) 
print(x)

tensor([[[[0.1817]]]])


In [ ]:
print(torch.zeros(1,1))

tensor([[0.]])


In [ ]:
print(torch.zeros(1,3))

tensor([[0., 0., 0.]])


In [ ]:
print(torch.zeros_like(torch.rand(2,2)))

tensor([[0., 0.],
        [0., 0.]])


In [ ]:
print(torch.ones_like(torch.rand(2,2)))

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(torch.ones(1,2))

tensor([[1., 1.]])


In [ ]:
print(torch.tensor([1,2,3]))

tensor([1, 2, 3])


In [ ]:
print(torch.tensor([1,2,3.]))

tensor([1., 2., 3.])


In [ ]:
print(torch.tensor([1,2,3.]).dtype)

torch.float32


In [ ]:
x = torch.tensor([1,2,3.])
y = torch.tensor([4,5,6.])

y.add_(x)
print(y)

tensor([5., 7., 9.])


In [ ]:
x = torch.tensor([1,2,3.])
y = torch.tensor([4,5,6.])
y.sub_(x)
print(y)

tensor([3., 3., 3.])


In [ ]:
x = torch.tensor([1,2,3.])
y = torch.tensor([4,5,6.])
y.mul_(x)
print(y)

tensor([ 4., 10., 18.])


In [ ]:
x = torch.tensor([1,2,3.])
y = torch.tensor([4,5,6.])
y.div_(x)
print(y)

tensor([4.0000, 2.5000, 2.0000])


In [ ]:
x = torch.rand(4,4)
y = x.view(-1, 8)
print(x)
print(y)

tensor([[0.6590, 0.5588, 0.5057, 0.7003],
        [0.6918, 0.7960, 0.7238, 0.9940],
        [0.3483, 0.9989, 0.4907, 0.0391],
        [0.5206, 0.9531, 0.7036, 0.5829]])
tensor([[0.6590, 0.5588, 0.5057, 0.7003, 0.6918, 0.7960, 0.7238, 0.9940],
        [0.3483, 0.9989, 0.4907, 0.0391, 0.5206, 0.9531, 0.7036, 0.5829]])


In [ ]:
print(y.size())

torch.Size([2, 8])


In [ ]:
print(x.view(8,-1))

tensor([[0.6590, 0.5588],
        [0.5057, 0.7003],
        [0.6918, 0.7960],
        [0.7238, 0.9940],
        [0.3483, 0.9989],
        [0.4907, 0.0391],
        [0.5206, 0.9531],
        [0.7036, 0.5829]])


In [ ]:
import torch as t
import numpy as np

x = t.rand(4,4)
print(x)
x.numpy()
print(type(x))

tensor([[0.9523, 0.7680, 0.7562, 0.0026],
        [0.4210, 0.7285, 0.6821, 0.5358],
        [0.9713, 0.1671, 0.6797, 0.8465],
        [0.7184, 0.6830, 0.7756, 0.7417]])
<class 'torch.Tensor'>


In [ ]:
y = x.numpy()
print(type(y))

<class 'numpy.ndarray'>


In [ ]:
x.add_(2) # trailing '_' function make changes inplace
print(x)
print(y)
#sharing same memory, be carefull

tensor([[2.9523, 2.7680, 2.7562, 2.0026],
        [2.4210, 2.7285, 2.6821, 2.5358],
        [2.9713, 2.1671, 2.6797, 2.8465],
        [2.7184, 2.6830, 2.7756, 2.7417]])
[[2.9522617 2.768019  2.756216  2.002638 ]
 [2.42099   2.7284646 2.6821234 2.535843 ]
 [2.9712543 2.1670613 2.679729  2.8465104]
 [2.7183785 2.683022  2.7755585 2.7417455]]


In [ ]:
# numpy can only handle tensors on cpu, so to convert to numpy array from tensor, that was on gpu. First we have to transfer all tensors to cpu